First stab at fixing demand type passed into cumulative constraint method + proto.
irfansharif/solver pull request #3
Opened 2021-09-17 06:30 UTC by smcheema

Still familiarizing myself with this repo, building off of : https://google.github.io/or-tools/java/CpModel_8java_source.html#l00897

2021-09-17 15:23 UTC, musanimu commented
Please change the data_driven.go file with the changed newCumalative Constraint function parameter, You will be passing a string from the data_driven.go function where as its supposed to accept an IntVar now

2021-09-17 15:53 UTC, irfansharif requested changes
Mostly looks good to me. Just a few minor suggestions.

2021-09-17 15:53 UTC, irfansharif commented on internal/testutils/parser/ast/ast.go
>  //   IntervalDemand = Identifier ":" Number .
Change Number to Identifier.

2021-09-17 15:53 UTC, irfansharif commented on internal/testutils/parser/grammar.ebnf
> +IntervalDemand = Identifier ":" Variable .
Should actually be Identifier instead. Variables are allowed to be of the form "a to b" which we don't want here.

2021-09-17 15:53 UTC, irfansharif commented on internal/testutils/parser/parser.go
> +	demand.Demand = p.Variable()
This will change to Identifier().

2021-09-17 15:53 UTC, irfansharif commented on internal/testutils/parser/testdata/statements
> +constrain.cumulative(i:dA, j:dB | C)
Could just use `d` here for both, this just checks that we can parse.

2021-09-17 15:53 UTC, irfansharif commented on internal/testutils/parser/testdata/units
> +x: dA
Same here, just use `d`.

2021-09-17 15:53 UTC, irfansharif commented on testdata/cumulative
> +constrain.cumulative(iA: dA, iB: dB, iC: dC | cap)
(These are fine to leave as is)

2021-09-17 15:53 UTC, irfansharif commented on testdata/print
> +model.constants(dA == 1)
Just use a single `d` here.

2021-09-17 15:53 UTC, irfansharif commented on testdata/recognize
> +constrain.cumulative(i: dA, j: dB | C)
Just use single `d` here.

2021-09-17 23:04 UTC, irfansharif reviewed
LGTM, can you squash all your commits and improve your commit message?

2021-09-17 23:18 UTC, smcheema commented
@irfansharif done

2021-09-18 00:22 UTC, irfansharif approved these changes
Thanks!

2021-09-18 00:31 UTC, merged